; The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

; Let us list the factors of the first seven triangle numbers:

;  1: 1
;  3: 1,3
;  6: 1,2,3,6
; 10: 1,2,5,10
; 15: 1,3,5,15
; 21: 1,3,7,21
; 28: 1,2,4,7,14,28
; We can see that 28 is the first triangle number to have over five divisors.

; What is the value of the first triangle number to have over five hundred divisors?
(def tris (drop 10000 (reductions + (range))))
(defn divisible? [n d] (zero? (mod n d)))

(defn n-factors [n]
    (let [r (range 2 (inc (Math/floor (Math/sqrt n))))        
          d (filter (partial divisible? n) r)
          sq (= (Math/pow (Math/floor (Math/sqrt n)) 2) (float n))
          c (+ (* 2 (count d))(if sq 1 2))]
      c))


(first (filter (fn [[n v]] (> n 500)) (pmap (juxt n-factors identity) tris)))
